default_joint_angles: # The default joint angles for the robot
  l_arm_shx: -1.570795
  r_arm_shx: 1.570795
  l_leg_hpy: 0.17453292519943295
  l_leg_kny: -0.34906585039886
  l_leg_aky: 0.17453292519943295
  r_leg_hpy: 0.17453292519943295
  r_leg_kny: -0.34906585039886
  r_leg_aky: 0.17453292519943295
  back_bky: 0.17453292519943295
kp: 2000.0 # Proportional gain for the PD controller
kd: 10.0 # Derivative gain for the PD controller
base_init_pos: [0.0, 0.0, 0.9] # Initial position of the robot base
base_init_quat: [1.0, 0.0, 0.0, 0.0] # Initial orientation of the robot base
episode_length_seconds: 20.0 # Length of the episode in seconds
resampling_time_seconds: 4.0 # Time between resampling the action
action_scale: 0.25 # Scale for the action space
simulate_action_latency: true # Whether to simulate action latency
clip_actions: 1.0 # Clip the action to a certain range
termination_if_roll_greater_than: 50.0
termination_if_pitch_greater_than: 50.0
